package com.app.pojos;

public enum SecurityQuestion {
	
	WHAT_IS_YOUR_FAVOURITE_FOOD,
	WHAT_WAS_YOUR_SCHOOL_ROLLNO,
	WHICH_SUBJECT_YOU_HATE_MOST,
	WHO_IS_YOUR_FAVOURITE_PERSON,
	WHICH_IS_YOUR_FAVOURITE_COLOR,
    WHICH_IS_YOUR_FAVOURITE_SONG,
    WHICH_IS_YOUR_FAVOURITE_MOVIE;
	
	
}
